# Generated by Django 3.2.9 on 2022-02-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220131_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_postman',
            field=models.BooleanField(default=False),
        ),
    ]
