# Generated by Django 3.2.9 on 2022-02-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220215_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CUSTOMER ', 'Customer'), ('MANAGER', 'Manager'), ('POSTMAN', 'Postman')], default='CUSTOMER', max_length=20),
        ),
    ]
