# Generated by Django 3.2.9 on 2022-02-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(help_text='13 digits cnic without -', max_length=13, unique=True),
        ),
    ]
