# Generated by Django 3.2.12 on 2022-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(help_text='13 digits cnic without -', max_length=13, unique=True),
        ),
    ]
