# Generated by Django 3.2.12 on 2022-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220316_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cnic',
            field=models.CharField(blank=True, help_text='13 digits cnic without -', max_length=13, null=True),
        ),
    ]
