# Generated by Django 3.2.9 on 2022-03-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default='Default', max_length=30, null=True),
        ),
    ]
