# Generated by Django 3.2.9 on 2022-02-16 14:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220216_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='qr_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 100*100 and format must be png image file', keep_meta=True, null=True, quality=75, size=[100, 100], upload_to='account/images/qrs/'),
        ),
    ]
