# Generated by Django 3.2.9 on 2022-02-16 15:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_parcel_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='qr_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='size of logo must be 100*100 and format must be png image file', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='account/images/qrs/'),
        ),
    ]
