# Generated by Django 3.2.12 on 2022-03-16 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_parcel_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='postman',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='sender',
        ),
        migrations.AddField(
            model_name='parcel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='destination_service_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_manager', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='source_service_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='status',
            field=models.CharField(default='cus', max_length=3),
        ),
    ]
