# Generated by Django 3.2.12 on 2022-03-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_postoffice_service_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoffice',
            name='parcels',
        ),
        migrations.AlterField(
            model_name='postoffice',
            name='office_address',
            field=models.CharField(max_length=255),
        ),
    ]
