# Generated by Django 3.2.12 on 2022-03-19 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_auto_20220316_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='destination_service_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
