# Generated by Django 3.2.9 on 2022-03-25 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220319_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postoffice',
            name='created_on',
        ),
        migrations.AddField(
            model_name='parcel',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_id',
            field=models.CharField(blank=True, default='481c736d', max_length=100, unique=True),
        ),
    ]
